### ISSUE TITLE
ID 9327 - Adicionar política de estatuto no menu de navegação

### ISSUE THREAD

**Issue by Isabel3012** [Isabel3012/Projetos-T-Up#48]

**Comment by Isabel3012** [comment]
# Feature: Criar novo menu "Estatuto" abaixo do menu "Política de Privacidade"

## ID - 9327

## Descrição

Adicionar um novo menu "Estatuto" abaixo do menu "Política de Privacidade" no painel lateral. Esse menu será visível apenas para usuários do tipo associado. Ao selecionar a opção, deverá ser chamada uma nova API que retorna o texto formatado em HTML, para ser exibido em tela de forma semelhante ao menu "Política de Privacidade".

## Passos para Reproduzir

1. Acesse o menu lateral da aplicação.
2. Se o usuário for do tipo "associado", o menu "Estatuto" deve ser exibido logo abaixo do menu "Política de Privacidade".
3. Ao selecionar o menu "Estatuto", a aplicação deve chamar o novo endpoint que retorna o conteúdo em HTML.
4. O conteúdo deve ser exibido em tela, semelhante ao que é feito com as "Políticas de Privacidade".

## Comportamento Esperado

- O menu "Estatuto" deve ser exibido apenas para usuários do tipo "associado".
- Ao clicar no menu "Estatuto", a aplicação deve chamar o endpoint e exibir o conteúdo retornado em HTML.

## Comportamento Atual

O menu "Estatuto" ainda não existe.

## Logs e Capturas de Tela (opcional)

- Imagem: Menu lateral onde o novo item "Estatuto" será adicionado.

![Image](https://github.com/user-attachments/assets/30a72a50-c47a-432d-aeee-765e2a301f9b)

## Informações Ambientais

- **Sistema Operacional**: Todos
- **Versão do Software**: Última versão em produção
- **Navegador** (se aplicável): Todos os navegadores
- **Outras Dependências**: 
  - Endpoint em homologação: `http://172.16.0.158:8082/swagger/ui/index#!/StatutePolicy/StatutePolicy_GetActiveStatute`
  - Endpoint em produção: ainda não publicado.

## Possível Solução (opcional)

1. Adicionar uma nova opção no menu lateral chamada "Estatuto", visível apenas para usuários associados.
2. Ao clicar no menu, fazer a chamada ao endpoint que retorna o estatuto ativo em HTML e exibir o conteúdo na tela.

## Prazo

7 horas

**Comment by eduarda551** [comment]
**Link da documentação dos testes:** [\[Santa Clara - Versão WEB\] - Inclusão da Politica de Estatuto no menu de navegação - Documentos Google (1).pdf](https://github.com/user-attachments/files/18212971/Santa.Clara.-.Versao.WEB.-.Inclusao.da.Politica.de.Estatuto.no.menu.de.navegacao.-.Documentos.Google.1.pdf)
